### ISSUE TITLE
Occasional 'Nernst' error

### ISSUE THREAD

**Issue by chen0gao** [ccnydss/bioanimation#51] opened 2019-02-04 15:42 UTC
`Uncaught TypeError: Cannot read property 'Nernst' of undefined
    at Question.init (Question.js:26)
    at NernstEq.start (NernstEq.js:24)
    at setup (main.js:53)
    at e.<anonymous> (p5.min.js:32)
    at e.<anonymous> (p5.min.js:32)
    at new e (p5.min.js:32)
    at e (p5.min.js:32)`

**Comment by alexmat2on** [comment] 2019-02-04 16:06
Likely caused by this async loadJSON call https://github.com/ccnydss/bioanimation/blob/master/js/obj/sim/Question.js#L7

When `init()` method is called, the JSON file probably has not loaded yet and thus `this.m_question_list` is a null reference. 

Might be fixed by loading the JSON file inside the `init()` method and performing the init logic inside the callback.

**Closed** 2019-04-15 17:50 UTC
Labels: bug
